baseURL = 'https://imted.netlify.app/'
languageCode = 'en-us'
title = "Ted's Blog"
theme = 'yinyang'
DefaultContentLanguage = "cn"

[params]
headTitle = "Ted's Blog"
description = 'Log something my writing'
favicon = "/favicon.ico"
extraHead = '<script async src="https://analytics.eu.umami.is/script.js" data-website-id="3755c68e-cfba-4b6a-85c4-654d790b9eea"></script>'

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "Github"
link = "https://github.com/preflower"

[languages]

[languages.cn]
contentDir = "content/cn"
languageName = "Chinese"
weight = 1
